server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthFilter
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**, /cart/**, /order/**
          filters:
            - JwtAuthFilter
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - JwtAuthFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/